# -*- coding: utf-8 -*-
"""StockMarket NSE Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uIvC6SUz-qU97jQtgrdc1XZFYal46SSU

## This is a new Stock Market data sheet

We will be fetching data for NSE website using the NSE tools

The Docs are : https://nsetools.readthedocs.io/en/latest/index.html
"""

from nselib import capital_market

# data = nselib.trading_holiday_calendar()
# data

data = capital_market.price_volume_and_deliverable_position_data(symbol='SBIN', from_date='19-04-2024', to_date='21-04-2024')
data

data = capital_market.price_volume_and_deliverable_position_data(symbol='INFY', from_date='19-04-2024', to_date='21-04-2024')
print(data)

capital_market.bhav_copy_equities("19-04-2024")

capital_market.bhav_copy_with_delivery("19-04-2024")

capital_market.block_deals_data(period = '1M')

capital_market.price_volume_and_deliverable_position_data("INFY", period = "1M")

capital_market.market_watch_all_indices()